### ISSUE TITLE
Exception attribute 'error' doesn't exist

### ISSUE THREAD

**Issue by bennoleslie** [reactjs/react-python#21]
When handling an execjs ProgramError, the code attempts to read the `message` attribute from the raised exception. The exception doesn't have any such attribute (causing a nested exception).

I'm not sure what the *right* fix is. I worked around be just doing `str(e)`, instead of `e.message` which at least unblocks me.

**Comment by kmeht** [comment]
Ah yeah, `BaseException.message` is deprecated. It's possible that it's been removed in the version of Python you're using. Using `str` is the way to go; we'd be happy to take a PR :)

**Comment by davidfischer-ch** [comment]
I guess you can close this issue because of a31de365db75f37a297f3d2dd81e482db6e14295.
