### ISSUE TITLE
Upgrade to React 0.13.1

### ISSUE THREAD

**Issue by henri-hulski** [reactjs/react-python#26]
Please upgrade to React 0.13.1.

**Comment by marioidival** [comment]
Why files of react.js was removed @kmeht ?

**Comment by kmeht** [comment]
@marioidival I'm using Bower to track the files now. I've been meaning to add a script to automatically download them so the community can include simple PRs to upgrade the React version.

**Comment by sontek** [comment]
@kmeht Any effort on making an upgrade?

**Comment by tarkatronic** [comment]
@kmeht I hate to echo @sontek's question, but this project is starting to look like it has been wholly abandoned. There has been no release on PyPi in over a year now (2014-11-24) and the React version is getting further and further behind now.

**Comment by kmeht** [comment]
Thanks for your interest, folks! This project is no longer maintained, and I've updated the README to reflect that. As of 0.14, JSXTransformer is deprecated and Babel is the recommended tool for transforming JSX, which obsoletes this project.

I've updated to the last version to support JSXTransformer (0.13.3) and uploaded it to PyPI: https://pypi.python.org/pypi/PyReact

**Comment by tarkatronic** [comment]
@kmeht That's great, as I was actually looking to use Babel. However, could you recommend a tool for integrating Babel with Django in a similar fashion as this project allowed? Instead of just saying this is no longer maintained, it would be great to recommend a path for moving forward.
